### ISSUE TITLE
bad babel options in extra/gulpfile.js

### ISSUE THREAD

**Issue by lcmtwn** [zordius/fluxex#5]
In https://github.com/zordius/fluxex/blob/master/extra/gulpfile.js#L234, bad babel options are passed in.

``` javascript
.pipe(babel(Object.assign({sourceMap: true}, configs.babelify)))
```

There are two problems. First, according to [babel options](https://babeljs.io/docs/usage/options/), it should be **sourceMaps** though there is no warning or error while sourceMap is used. Second, [babelify options](https://github.com/zordius/fluxex/blob/master/extra/gulpfile.js#L72-76) are used as babel options however the **extensions** option is not babel option. This fails the gulp task while extra/gulpfile.js is required in project gulpfile.js and no other changes are made. Since there are not many options for babel it may just defines the options in separate variable or in https://github.com/zordius/fluxex/blob/master/extra/gulpfile.js#L234.

**Comment by zordius** [comment]
Good point! thank you for your reporting! I will work on this later.

**Comment by zordius** [comment]
After 954fe1d8854c17707abdafec63d103ec9d0daecb , babel and babelify options should be handled correctly in different place. Please try again, thanks.
